# Copyright (c) 2023-24 Harman International.
# SPDX-License-Identifier: Apache-2.0
FROM azul/zulu-openjdk-alpine:17.0.9-17.46.19-jre-headless
LABEL authors="https://accounts.eclipse.org/mailing-list/ecsp-dev"
